### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by DanielZlotin** [react-native-community/jsc-android-buildscripts#141]
It's been 2 years since I stopped actively maintaining this project,
cc @Kudo @kmagiera if you guys dropped as well (and thank you for all your work 👍  🥇  ), how about we add a "not maintained" warning in the README?

**Comment by mrueger42** [comment]
although I'm using the libraries for a non React project I unfortunately don't have the skillset to maintain this project.

What are people moving on to from here? Hermes? NodeJS?

And, yes, huge thanks to the maintainers here!

**Comment by Kudo** [comment]
Actually I had some new updates on my [fork](https://github.com/Kudo/jsc-android-buildscripts/), because I did not have permission to fix the broken CI and npm permission to publish new version.

However, I do not have much time to maintain this as well.
Once Hermes supports Intl and Proxy well and react-native uses Hermes by default.
I would suggest to have a stable JSC version and freeze the updates if there are no maintainers.

**Comment by Kudo** [comment]
Thank @kmagiera for granting me permission.
I will maintain this repo for a while until Hermes replaced JSC as default engine for RN.
I am going to close this issue.
